# Generated by Django 5.0.4 on 2024-04-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='No subject', max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
